# Generated by Django 5.0.2 on 2024-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'This username is already registered'}, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('utype', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Users/')),
                ('dob', models.DateField()),
                ('kin', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('username', models.CharField(error_messages={'unique': 'This username is already registered.'}, max_length=100, unique=True)),
            ],
        ),
    ]
