# Generated by Django 5.0.2 on 2024-12-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0003_medicine_reminder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('medicine', 'time', 'dose', 'user')},
        ),
    ]
