# Generated by Django 5.0.2 on 2024-12-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0004_alter_medicine_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
