# Generated by Django 5.0.2 on 2024-12-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0007_alter_medicine_status_alter_reminder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
    ]
