# Generated by Django 5.0.2 on 2024-12-27 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0008_remove_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
