# Generated by Django 5.0.2 on 2024-12-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0009_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
    ]
