# Generated by Django 3.2.12 on 2025-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0011_kin_unknown_faces'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='unknown_faces')),
            ],
        ),
        migrations.DeleteModel(
            name='unknown_faces',
        ),
    ]
