# Generated by Django 5.0.2 on 2024-12-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
    ]
