# Generated by Django 5.0.2 on 2024-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0005_alter_medicine_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(max_length=100),
        ),
    ]
