# Generated by Django 5.0.2 on 2024-12-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0006_alter_medicine_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
